# SWISTART

KBUILD_CPPFLAGS += -I$(src)/api

obj-$(CONFIG_SIERRA) += src/ssmem_core.o
obj-$(CONFIG_SIERRA) += src/ssmem_linux.o
obj-$(CONFIG_SIERRA) += src/ssmem_user.o
obj-$(CONFIG_SIERRA) += src/ssmem_utils.o
obj-$(CONFIG_SIERRA) += src/ssmem_bscommon.o

obj-$(CONFIG_KEYS_KEYSTORE) += src/ssmem_keystore.o

# SWISTOP
